---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    data_bags_path: "test/integration/data_bags"
    run_list:
      - recipe[maxscale::default]
    attributes:
      maxscale:
        databag:
          enabled: true
        config:
          maxscale:
            threads: 2
            log_debug: 1
            log_trace: 1
          db1:
            type: 'server'
            address: '127.0.0.11'
            port: 3306
            protocol: 'MySQLBackend'
          db2:
            type: 'server'
            address: '127.0.0.12'
            port: 3306
            protocol: 'MySQLBackend'
          db3:
            type: 'server'
            address: '127.0.0.13'
            port: 3306
            protocol: 'MySQLBackend'
          db4:
            type: 'server'
            address: '127.0.0.14'
            port: 3306
            protocol: 'MySQLBackend'
          db5:
            type: 'server'
            address: '127.0.0.15'
            port: 3306
            protocol: 'MySQLBackend'
